
version: '2.13.0'

services:
  mariadb:
    build: ./mariadb
    container_name: mariadb
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mariadb-data:/var/lib/mysql
  
  nginx:
    build: ./nginx
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - "443:443"
    depends_on:
      - mariadb
      - wordpress
    networks:
      - app-network
    volumes:
      - wordpress-data:/var/www/html

  wordpress:
    build: ./wordpress
    container_name: wordpress
    image: wordpress
    restart: always
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    networks:
      - app-network
    volumes:
      - wordpress-data:/var/www/html

volumes:
  wordpress-data:
    name: wordpress-data
    driver: local
    driver_opts:
      type: none
      device: /Users/shbi/Desktop/volume_wp/
      o: bind
  mariadb-data:
    name: mariadb-data
    driver: local
    driver_opts:
      type: none
      device: /Users/shbi/Desktop/volume_mdb/
      o: bind
networks:
  app-network: